# Site settings
title: Dodam Lab | A simple dodam blog
description: "A minimal blog template, build with Jekyll."
url: "http://cloone1224.github.io/dodam-blog"
author:
  name: "YoungChan Lee"
  email: "cloone1224@gmail.com"
  url: "http://cloone1224.github.io/dodam-blog"

# Build settings
baseurl: /dodam-blog/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
#theme: emerald
plugins: [jekyll-paginate-v2]
exclude:
    - Gemfile
    - Gemfile.lock
    
#paginate: nil
#paginate_path: nil
    
# Produces a cleaner folder structure when using categories
permalink: /:year/:month/:title.html

# Pagination Settings
pagination:
  enabled: true
  per_page: 8
  permalink: '/page:num/'
  #permalink: '/page/:num/'
  #title: ':title - page :num of :max'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

source: .
destination: ./_site

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
   
# Disqus Comments
disqus:
    shortname: dodam-blog
    enable: true