# Site settings
title: Dodam Lab | A simple dodam blog
description: "A minimal blog template, build with Jekyll."
url: "http://cloone1224.github.io/dodam-blog"
author:
  name: "YoungChan Lee"
  email: "cloone1224@gmail.com"
  url: "http://cloone1224.github.io/dodam-blog"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
