# Site settings
title: Dodam Lab | A simple dodam blog
description: "A minimal blog template, build with Jekyll."
url: "http://cloone1224.github.io/dodam-blog"
author:
  name: "YoungChan Lee"
  email: "cloone1224@gmail.com"
  url: "http://cloone1224.github.io/dodam-blog"

# Build settings
baseurl: /dodam-blog/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
#theme: emerald
#gems:
#    - jekyll-paginate
#exclude:
#    - Gemfile
#    - Gemfile.lock
source: .
destination: ./_site
#permalink: /:year/:month/:title.html
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

plugins: [jekyll-paginate]
   
#pagination:
#    enabled: true
#    per_page: 2
#    permalink: '/page/:num/'
#    title: ' - page :num'
#    limit: 0
#    sort_field: 'date'
#    sort_reverse: true

# Disqus Comments
disqus:
    shortname: dodam-blog
    enable: true
